DROP TABLE IF EXISTS ST_SSO_BIND;
DROP TABLE IF EXISTS ST_SSO_AUTH;
DROP TABLE IF EXISTS ST_SSO_ACCOUNT;

CREATE TABLE ST_SSO_ACCOUNT (
  ID SERIAL NOT NULL,
  STATUS_ INT NOT NULL,
  CODE_ VARCHAR(50) NOT NULL UNIQUE,
  NAME_ VARCHAR(50) NOT NULL,
  ALIAS_ VARCHAR(50),
  PRIMARY KEY (ID)
);
COMMENT ON TABLE ST_SSO_ACCOUNT IS '帐号';
COMMENT ON COLUMN ST_SSO_ACCOUNT.STATUS_ IS '状态 0-待审 1-正常 2-禁用';
COMMENT ON COLUMN ST_SSO_ACCOUNT.CODE_ IS '主号';
COMMENT ON COLUMN ST_SSO_ACCOUNT.NAME_ IS '姓名';
COMMENT ON COLUMN ST_SSO_ACCOUNT.ALIAS_ IS '别名';

CREATE TABLE ST_SSO_AUTH (
  PID INT NOT NULL,
  TYPE_ VARCHAR(10) NOT NULL,
  DATA_ TEXT NOT NULL,
  PRIMARY KEY (PID, TYPE_),
  FOREIGN KEY (PID) REFERENCES ST_SSO_ACCOUNT (ID)
);
COMMENT ON TABLE ST_SSO_AUTH IS '认证';
COMMENT ON COLUMN ST_SSO_AUTH.TYPE_ IS '认证方式，如 md5';
COMMENT ON COLUMN ST_SSO_AUTH.DATA_ IS '认证数据，如密码的 md5 值';

CREATE TABLE ST_SSO_BIND (
  PID INT NOT NULL,
  TYPE_ VARCHAR(10) NOT NULL,
  CODE_ VARCHAR(50) NOT NULL,
  PRIMARY KEY (TYPE_, CODE_),
  FOREIGN KEY (PID) REFERENCES ST_SSO_ACCOUNT (ID)
);
COMMENT ON TABLE ST_SSO_BIND IS '绑定号';
COMMENT ON COLUMN ST_SSO_BIND.TYPE_ IS '类别，如 mobile-手机、email-邮箱、qq-QQ帐号';
COMMENT ON COLUMN ST_SSO_BIND.CODE_ IS '绑定号，注：同一手机、邮箱等不可以绑定到不同的帐号，但同一帐号可以绑定多个手机、邮箱等';

-- admin|tester
DELETE FROM ST_SSO_AUTH;
DELETE FROM ST_SSO_ACCOUNT;
INSERT INTO ST_SSO_ACCOUNT(STATUS_, CODE_, NAME_, ALIAS_) VALUES
  (1, 'admin', 'Admin', '系统管理员'),
  (1, 'tester', '测试员', null);
INSERT INTO ST_SSO_AUTH(PID, TYPE_, DATA_) VALUES
  -- admin|admin123|0192023a7bbd73250516f069df18b500
	((SELECT ID FROM ST_SSO_ACCOUNT WHERE CODE_ = 'admin'), 'md5', md5('admin123')),
  -- tester|888888|21218cca77804d2ba1922c33e0151105
	((SELECT ID FROM ST_SSO_ACCOUNT WHERE CODE_ = 'tester'), 'md5', md5('888888'));
INSERT INTO ST_SSO_BIND(PID, TYPE_, CODE_) VALUES
  ((SELECT ID FROM ST_SSO_ACCOUNT WHERE CODE_ = 'admin'), 'mobile', '13611112222'),
  ((SELECT ID FROM ST_SSO_ACCOUNT WHERE CODE_ = 'admin'), 'mobile', '13622223333'),
  ((SELECT ID FROM ST_SSO_ACCOUNT WHERE CODE_ = 'admin'), 'email', 'admin@simter.org');

SELECT * FROM ST_SSO_ACCOUNT A
  INNER JOIN ST_SSO_AUTH T ON T.PID = A.ID
  LEFT JOIN ST_SSO_BIND B ON B.PID = A.ID;

--select * from bc_identity_auth t inner join bc_identity_actor a on a.id = t.id where a.code='admin';